### ISSUE TITLE
version-check only gives me an error "Unsupported protocol"

### ISSUE THREAD

**Issue by LMS007** [Gaimglass/gg-console#1]
I have a pretty simple workflow but it does not work

```
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
```

Error: 
```
Run EndBug/version-check@v2
  with:
    diff-search: false
    file-name: package.json
    token: ***
    github-api-url: https://api.github.com/
  env:
    GITHUB_TOKEN: ***
Searching for version update...
Error: Unsupported protocol "d:"
```
